project:
  type: website

website:
  title: "Introduction into Atomic, Molecular, and Optical Physics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: contents.qmd
        text: Contents
      - href: about.qmd
        text: About
  reader-mode: true
  sidebar:
    style: "floating"
    collapse-level: 1
    search: true
    contents:
      - text: "Home"
        href: index.qmd
#      - section: "Basics"
#        href: basics-summary.qmd
#        contents:
#          - index.qmd
#          - basics-knitr.qmd
#          - basics-jupyter.qmd
      - section: "Quantum Mechanics"
        href: mod2/index.qmd
        contents:
          - mod2/wavemechanics.qmd
          - mod2/braket.qmd
          - mod2/heisenberg.qmd
          - mod2/perturb.qmd
          - mod4/relwaves.qmd            
      - section: "Hydrogen (Basics)"
        href: mod3/index.qmd
        contents:
          - mod3/angmom.qmd
          - mod3/hydrogen.qmd
      - section: "Hydrogen (Details)"
        href: mod4/index.qmd
        contents:
          - mod4/spin.qmd
          - mod4/lamb.qmd
          - mod4/hfs.qmd
          - mod4/summary.qmd
          - mod4/fields.qmd
      - section: "Absorption and Emission of Radiation"
        contents:
          - mod5/einstein.qmd
          - mod5/dipolematrix.qmd


#      - section: advanced.qmd
#        contents:
#          - raw-code.qmd
#          - custom-theme.qmd
#      - acknowledgment.qmd

lightbox: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    embed-resources: true
    self-contained: true
    fig-alt: true
    html-math-method: mathjax