project:
  type: website

website:
  title: "Introduction into Atomic, Molecular, and Optical Physics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: contents.qmd
        text: Contents
      - href: about.qmd
        text: About
  reader-mode: true
  sidebar:
    style: "floating"
    collapse-level: 1
    search: true
    contents:
      - text: "Home"
        href: index.qmd
#      - section: "Basics"
#        href: basics-summary.qmd
#        contents:
#          - index.qmd
#          - basics-knitr.qmd
#          - basics-jupyter.qmd
      - section: "Quantum Mechanics"
        href: mod2/index.qmd
        contents:
          - mod2/wavemechanics.qmd
          - mod2/braket.qmd
          - mod2/measurement.qmd
          - mod2/heisenberg.qmd
          - mod2/amcoupling.qmd
          - mod2/qosc.qmd
          - mod2/perturb.qmd
          - mod2/variational.qmd
          - mod2/exchange.qmd
          - mod4/relwaves.qmd            
      - section: "Hydrogen Atom: Wave Functions"
        href: mod3/index.qmd
        contents:
          - mod3/angmom.qmd
          - mod3/hydrogen.qmd
      - section: "Hydrogen Atom: Shifts and Interactions"
        href: mod4/index.qmd
        contents:
          - mod4/spin.qmd
          - mod4/lamb.qmd
          - mod4/hfs.qmd
          - mod4/summary.qmd
          - mod4/fields.qmd
      - section: "Absorption and Emission of Radiation"
        href: mod5/index.qmd
        contents:
          - mod5/einstein.qmd
          - mod5/dipolematrix.qmd
          - text: "Visualizing Atomic Transitions"
            href: mod5/visual.qmd
          - mod5/selectionr.qmd
          - mod5/spectroscopy.qmd
          - mod5/dopplerfree.qmd
      - section: "More than One Electron Atoms"
        href: mod6/index.qmd
        contents:
          - mod6/helium.qmd
          - mod6/twoelectron.qmd
          - mod6/hartreefock.qmd
          - mod6/manye.qmd
          - mod6/coupling.qmd
          - mod6/excited.qmd
      - section: "Introduction to Molecular Physics"   
        href: mod7/index.qmd
        contents:
          - mod7/molfound.qmd
          - mod7/h2plus.qmd
          - mod7/lcao.qmd
          - mod7/beyondh2plus.qmd
          - mod7/nuclear.qmd
          - mod7/moltransitions.qmd
      - section: "Laser–Atom Interactions"   
        href: mod8/index.qmd
        contents:
          - mod8/twoleveltheory.qmd
          - mod8/rwa_rabi.qmd
          - mod8/densitym.qmd
          - mod8/obe.qmd
          - mod8/cooling.qmd
          - mod8/bloch.qmd
          - mod8/ramsey.qmd


#      - section: advanced.qmd
#        contents:
#          - raw-code.qmd
#          - custom-theme.qmd
#      - acknowledgment.qmd

lightbox: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    embed-resources: true
    self-contained: true
    fig-alt: true
    html-math-method: mathjax
#    include-in-header:
#      - file: delay-mathjax.js