---
title: Table of Contents
author: Daniel Fischer
---


This page provides an overview and links to all the sections of the website.

---

## [Quantum Mechanics](mod2/index.qmd)

* [Wave Mechanics](mod2/wavemechanics.qmd)
* [States and Operators in Quantum Mechanics](mod2/braket.qmd)
* [Quantum Measurement and the Measurement Problem](mod2/measurement.qmd)
* [Commutators and the Heisenberg Uncertainty Principle](mod2/heisenberg.qmd)
* [Angular Momenta and Their Couplings](mod2/amcoupling.qmd)
* [The One-Dimensional Quantum Harmonic Oscillator](mod2/qosc.qmd)
* [Time-Independent Perturbation Theory](mod2/perturb.qmd)
* [Time-Dependent Perturbation Theory and Fermi’s Golden Rule](mod2/tdperturb.qmd)
* [The Variational Method](mod2/variational.qmd)
* [Exchange Interaction: Fermions and Bosons](mod2/exchange.qmd)
* [Relativistic Wave Equations — the Dirac Equation](mod4/relwaves.qmd)

---

## [Hydrogen Atom: Wave Functions](mod3/index.qmd)

* [Orbital Angular Momentum in Quantum Mechanics](mod3/angmom.qmd)
* [Hydrogen atom — Schrödinger equation and radial solutions](mod3/hydrogen.qmd)
* [Visualizing Hydrogen Orbitals](mod3/orbitals.qmd)

---

## [Hydrogen Atom: Shifts and Interactions](mod4/index.html)

* [Electron Spin and Fine Structure](mod4/spin.qmd)
* [The Lamb Shift — An Introduction to Quantum Electrodynamics](mod4/lamb.qmd)
* [The Hyperfine Structure (HFS)](mod4/hfs.qmd)
* [Summary — energy-level splitting](mod4/summary.qmd)
* [Hydrogen in Static External Fields](mod4/fields.qmd)

---

## [Absorption and Emission of Radiation](mod5/index.qmd)  

* [Transition processes and Einstein Coefficients](mod5/einstein.qmd)
* [Spontaneous Decay and Atomic Transition Rates](mod5/dipolematrix.qmd)
* [Visualizing Atomic Transitions](mod5/visual.qmd)
* [Radiation and Selection Rules](mod5/selectionr.qmd)
* [Spectroscopy and Spectral Line Widths](mod5/spectroscopy.qmd)
* [Doppler-Free Saturation Spectroscopy](mod5/dopplerfree.qmd)

---

## [More than One Electron Atoms](mod6/index.qmd)  

* [Helium (Basics)](mod6/helium.qmd)
* [Two-Electron States in Helium](mod6/twoelectron.qmd)
* [Calculations for Multielectron Atoms](mod6/hartreefock.qmd)
* [Shell Model and Periodic Table](mod6/manye.qmd)
* [Angular Momentum Coupling in Many Electron Atoms](mod6/coupling.qmd)
* [Excited States](mod6/excited.qmd)

---

## [Introduction to Molecular Physics](mod7/index.qmd)  

* [Foundations of Molecular Bonding](mod7/molfound.qmd)
* [The H$_2^+$ Molecular Ion](mod7/h2plus.qmd)
* [Molecular Orbitals and the LCAO Method](mod7/lcao.qmd)
* [Beyond H$_2^+$ and LCAO](mod7/beyondh2plus.qmd)
* [Rotation and Vibration](mod7/nuclear.qmd)
* [Molecular Transitions and Spectroscopy](mod7/moltransitions.qmd)

---

## [Laser–Atom Interactions](mod8/index.qmd) 

* [Two-Level Systems — The Theoretical Framework](mod8/twoleveltheory.qmd)
* [Rotating Wave Approximation and Rabi Oscillations](mod8/rwa_rabi.qmd)
* [The Density Matrix Formalism](mod8/densitym.qmd)
* [The Optical Bloch Equations](mod8/obe.qmd)
* [Laser Cooling](mod8/cooling.qmd)
* [The Bloch Sphere Representation](mod8/bloch.qmd)
* [Ramsey Spectroscopy and Atomic Clocks](mod8/ramsey.qmd)

